import React from 'react';
import './index.css';

export default function TaxAgency() {
    return (
      <div className="lawBox">
      <p className="p1"><span className="s1"><strong>세무신고대리</strong></span><span className="s2"><strong>&nbsp;</strong></span><span className="s1"><strong>계약서</strong></span></p>
      <p className="p2"><br /></p>
      <p className="p3">본<span className="s3">&nbsp;</span>계약서는<span className="s3">&nbsp;</span>세무<span className="s3">&nbsp;</span>관련<span className="s3">&nbsp;</span>업무처리<span className="s3">&nbsp;IT</span>솔루션을<span className="s3">&nbsp;</span>제공하는<span className="s3">&nbsp;</span>㈜택사스소프트<span className="s3">(</span>이하<span className="s3">&nbsp;“IT</span>솔루션사<span className="s3">”</span>라<span className="s3">&nbsp;</span>한다<span className="s3">)</span>가<span className="s3">&nbsp;</span>제공하는<span className="s3">&nbsp;</span>부가가치세신고신청웹서비스<span className="s3">(</span>이하<span className="s3">&nbsp;“</span>웹서비스<span className="s3">”</span>라<span className="s3">&nbsp;</span>한다<span className="s3">)</span>을<span className="s3">&nbsp;</span>이용하고자<span className="s3">&nbsp;</span>개인정보를<span className="s3">&nbsp;</span>입력한<span className="s3">&nbsp;</span>이용자<span className="s3">(</span>이하<span className="s3">&nbsp;“</span>갑<span className="s3">”</span>이라<span className="s3">&nbsp;</span>한다<span className="s3">)</span>와<span className="s3">&nbsp;IT</span>솔루션사와<span className="s3">&nbsp;</span>제휴<span className="s3">&nbsp;</span>계약을<span className="s3">&nbsp;</span>맺은<span className="s3">&nbsp;</span>세무법인다솔<span className="s3">&nbsp;</span>반포중앙지점<span className="s3">(</span>이하<span className="s3">&nbsp;“</span>을<span className="s3">”</span>이라<span className="s3">&nbsp;</span>한다<span className="s3">)&nbsp;</span>간의<span className="s3">&nbsp;</span>세무대리<span className="s3">&nbsp;</span>수임<span className="s3">&nbsp;</span>계약에<span className="s3">&nbsp;</span>필요한<span className="s3">&nbsp;</span>규율을<span className="s3">&nbsp;</span>정하고<span className="s3">&nbsp;</span>아래<span className="s3">&nbsp;</span>내용과<span className="s3">&nbsp;</span>같이<span className="s3">&nbsp;</span>계약하기로<span className="s3">&nbsp;</span>합니다<span className="s3">. <span className="Apple-converted-space">&nbsp;</span></span></p>
      <p className="p2"><br /></p>
      <ol className="ol1">
        <li className="li4"><span className="s4"><strong>위임업무</strong></span></li>
      </ol>
      <p className="p3">갑은<span className="s3">&nbsp;</span>을을<span className="s3">&nbsp;</span>대리인으로<span className="s3">&nbsp;</span>지정하여<span className="s3">&nbsp;</span>세무대리업무를<span className="s3">&nbsp;</span>위임하고<span className="s3">,&nbsp;</span>을은<span className="s3">&nbsp;</span>이를<span className="s3">&nbsp;</span>수임합니다<span className="s3">.</span></p>
      <ol className="ol1">
        <li className="li3"><span className="s3">“</span>신고대리<span className="s3">”</span>란<span className="s3">&nbsp;</span>갑과<span className="s3">&nbsp;</span>세금신고와<span className="s3">&nbsp;</span>관련하여<span className="s3">&nbsp;</span>조세법에<span className="s3">&nbsp;</span>따른<span className="s3">&nbsp;</span>갑의<span className="s3">&nbsp;</span>과세표준<span className="s3">&nbsp;</span>등의<span className="s3">&nbsp;</span>세금신고를<span className="s3">&nbsp;</span>위해<span className="s3">&nbsp;</span>을이<span className="s3">&nbsp;</span>수행하는<span className="s3">&nbsp;</span>신고서<span className="s3">&nbsp;</span>대리작성<span className="s3">&nbsp;</span>업무를<span className="s3">&nbsp;</span>말합니다<span className="s3">.</span></li>
        <li className="li3">세무대리<span className="s3">&nbsp;</span>업무에<span className="s3">&nbsp;</span>한정하여<span className="s3">&nbsp;</span>계약을<span className="s3">&nbsp;</span>하며<span className="s3">&nbsp;</span>신고대리<span className="s3">&nbsp;</span>업무<span className="s3">&nbsp;</span>외에<span className="s3">&nbsp;</span>세무자문<span className="s3">,&nbsp;</span>세무조정<span className="s3">&nbsp;</span>및<span className="s3">&nbsp;</span>기장<span className="s3">&nbsp;</span>대리와<span className="s3">&nbsp;</span>관련한<span className="s3">&nbsp;</span>업무<span className="s3">&nbsp;</span>범위는<span className="s3">&nbsp;</span>포함하지<span className="s3">&nbsp;</span>않습니다<span className="s3">.&nbsp;</span>만약<span className="s3">&nbsp;</span>갑이<span className="s3">&nbsp;</span>앞서<span className="s3">&nbsp;</span>열거한<span className="s3">&nbsp;</span>세무업무를<span className="s3">&nbsp;</span>의뢰하고자<span className="s3">&nbsp;</span>한다면<span className="s3">&nbsp;IT</span>솔루션사를<span className="s3">&nbsp;</span>통하지<span className="s3">&nbsp;</span>않고<span className="s3">&nbsp;</span>별도의<span className="s3">&nbsp;</span>상담<span className="s3">&nbsp;</span>및<span className="s3">&nbsp;</span>협의를<span className="s3">&nbsp;</span>통하여<span className="s3">&nbsp;</span>수수료와<span className="s3">&nbsp;</span>업무범위를<span className="s3">&nbsp;</span>정하기로<span className="s3">&nbsp;</span>합니다<span className="s3">.</span></li>
      </ol>
      <p className="p5"><br /></p>
      <ol className="ol1">
        <li className="li4"><span className="s4"><strong>수수료</strong></span><strong>&nbsp;</strong><span className="s4"><strong>확정</strong></span></li>
        <li className="li3">본<span className="s3">&nbsp;</span>계약에<span className="s3">&nbsp;</span>따른<span className="s3">&nbsp;</span>세무신고대행<span className="s3">&nbsp;</span>수수료는<span className="s3">&nbsp;</span>갑의<span className="s3">&nbsp;</span>과세자료의<span className="s3">&nbsp;</span>양과<span className="s3">&nbsp;</span>범위에<span className="s3">&nbsp;</span>따라서<span className="s3">&nbsp;</span>을이<span className="s3">&nbsp;</span>정한<span className="s3">&nbsp;</span>수수료<span className="s3">&nbsp;</span>기준에<span className="s3">&nbsp;</span>의거하여<span className="s3">&nbsp;</span>이용자에게<span className="s3">&nbsp;</span>제안되며<span className="s3">,&nbsp;</span>갑은<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약<span className="s3">&nbsp;</span>전에<span className="s3">&nbsp;</span>수수료를<span className="s3">&nbsp;</span>확인한<span className="s3">&nbsp;</span>후에<span className="s3">&nbsp;</span>위임에<span className="s3">&nbsp;</span>동의하기로<span className="s3">&nbsp;</span>합니다<span className="s3">.&nbsp;</span>단<span className="s3">,&nbsp;</span>해당<span className="s3">&nbsp;</span>수수료<span className="s3">&nbsp;</span>정보는<span className="s3">&nbsp;IT</span>솔루션사를<span className="s3">&nbsp;</span>통해서<span className="s3">&nbsp;</span>문자메시지로<span className="s3">&nbsp;</span>갑에게<span className="s3">&nbsp;</span>전달되며<span className="s3">&nbsp;</span>입금<span className="s3">&nbsp;</span>확인<span className="s3">&nbsp;</span>시<span className="s3">,&nbsp;</span>갑은<span className="s3">&nbsp;</span>본인의<span className="s3">&nbsp;</span>수수료를<span className="s3">&nbsp;</span>확인한<span className="s3">&nbsp;</span>것으로<span className="s3">&nbsp;</span>간주됩니다<span className="s3">.</span></li>
      </ol>
      <p className="p2"><br /></p>
      <ol className="ol1">
        <li className="li3"><strong>수수료의</strong><span className="s3"><strong>&nbsp;</strong></span><strong>지급방법</strong><span className="s3"><strong>&nbsp;</strong></span><strong>및</strong><span className="s3"><strong>&nbsp;</strong></span><strong>시기</strong></li>
        <li className="li3">이<span className="s3">&nbsp;</span>신고대리<span className="s3">&nbsp;</span>업무는<span className="s3">&nbsp;</span>앱서비스를<span className="s3">&nbsp;</span>통해서<span className="s3">&nbsp;</span>비대면으로<span className="s3">&nbsp;</span>처리되기<span className="s3">&nbsp;</span>때문에<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약을<span className="s3">&nbsp;</span>통해<span className="s3">&nbsp;</span>진행되는<span className="s3">&nbsp;</span>수수료는<span className="s3">&nbsp;</span>선<span className="s3">&nbsp;</span>결제되며<span className="s3">,&nbsp;</span>본<span className="s3">&nbsp;</span>계약<span className="s3">&nbsp;</span>체결과<span className="s3">&nbsp;</span>동시에<span className="s3">&nbsp;</span>이용자는<span className="s3">&nbsp;</span>선결제방식에<span className="s3">&nbsp;</span>동의한<span className="s3">&nbsp;</span>것으로<span className="s3">&nbsp;</span>간주됩니다<span className="s3">.</span></li>
        <li className="li3">갑이<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약범위<span className="s3">&nbsp;</span>내에서의<span className="s3">&nbsp;</span>세무업무에<span className="s3">&nbsp;</span>대한<span className="s3">&nbsp;</span>세금계산서<span className="s3">&nbsp;</span>발행을<span className="s3">&nbsp;</span>요청하는<span className="s3">&nbsp;</span>경우<span className="s3">,&nbsp;</span>을은<span className="s3">&nbsp;</span>지체없이<span className="s3">&nbsp;</span>해당<span className="s3">&nbsp;</span>세무대리업무<span className="s3">&nbsp;</span>수수료에<span className="s3">&nbsp;</span>대한<span className="s3">&nbsp;</span>세금계산서를<span className="s3">&nbsp;</span>발행하여<span className="s3">&nbsp;</span>제공합니다<span className="s3">.<br /></span></li>
        <li className="li4"><span className="s4"><strong>환불정책</strong></span></li>
        <li className="li3">갑은<span className="s3">&nbsp;</span>을에게<span className="s3">&nbsp;</span>환불을<span className="s3">&nbsp;</span>요청할<span className="s3">&nbsp;</span>수<span className="s3">&nbsp;</span>있고<span className="s3">,&nbsp;</span>갑이<span className="s3">&nbsp;</span>안내하는<span className="s3">&nbsp;</span>환불<span className="s3">&nbsp;</span>정책에<span className="s3">&nbsp;</span>따라<span className="s3">&nbsp;</span>진행이<span className="s3">&nbsp;</span>됩니다<span className="s3">.<span className="Apple-converted-space">&nbsp;</span></span></li>
        <li className="li3">환불이<span className="s3">&nbsp;</span>가능한<span className="s3">&nbsp;</span>기간은<span className="s3">&nbsp;</span>다음과<span className="s3">&nbsp;</span>같으며<span className="s3">,&nbsp;</span>해당<span className="s3">&nbsp;</span>신고분<span className="s3">&nbsp;</span>수수료의<span className="s3">&nbsp;100%&nbsp;</span>환불이<span className="s3">&nbsp;</span>가능합니다<span className="s3">.<br /></span>정기신고<span className="s3">&nbsp;:&nbsp;</span>신청일로부터<span className="s3">&nbsp;3</span>일<span className="s3">&nbsp;</span>이내</li>
        <li className="li3">환불이<span className="s3">&nbsp;</span>가능한<span className="s3">&nbsp;</span>조건은<span className="s3">&nbsp;</span>다음과<span className="s3">&nbsp;</span>같습니다<span className="s3">.<br /></span>갑이<span className="s3">&nbsp;</span>신고<span className="s3">&nbsp;</span>취소를<span className="s3">&nbsp;</span>원하는<span className="s3">&nbsp;</span>경우<span className="s3">,&nbsp;</span>신고<span className="s3">&nbsp;</span>취소<span className="s3">&nbsp;</span>접수증<span className="s3">&nbsp;</span>또는<span className="s3">&nbsp;</span>신규<span className="s3">&nbsp;</span>접수증을<span className="s3">&nbsp;</span>제출하는<span className="s3">&nbsp;</span>경우에<span className="s3">&nbsp;</span>한하여<span className="s3">&nbsp;</span>환불을<span className="s3">&nbsp;</span>진행하며<span className="s3">,&nbsp;</span>을에게<span className="s3">&nbsp;</span>귀책사유가<span className="s3">&nbsp;</span>있는<span className="s3">&nbsp;</span>신고내용의<span className="s3">&nbsp;</span>오류<span className="s3">,&nbsp;</span>서비스<span className="s3">&nbsp;</span>프로세스<span className="s3">&nbsp;</span>상의<span className="s3">&nbsp;</span>오류가<span className="s3">&nbsp;</span>발생한<span className="s3">&nbsp;</span>경우<span className="s3">&nbsp;</span>환불을<span className="s3">&nbsp;</span>진행합니다<span className="s3">.</span></li>
        <li className="li3">환불이<span className="s3">&nbsp;</span>불가능한<span className="s3">&nbsp;</span>조건은<span className="s3">&nbsp;</span>다음과<span className="s3">&nbsp;</span>같습니다<span className="s3"><br /></span>을에게<span className="s3">&nbsp;</span>취소<span className="s3">&nbsp;</span>요청<span className="s3">&nbsp;</span>없이<span className="s3">&nbsp;</span>직접<span className="s3">&nbsp;</span>홈택스<span className="s3">&nbsp;</span>또는<span className="s3">&nbsp;</span>세무서를<span className="s3">&nbsp;</span>통해<span className="s3">&nbsp;</span>다시<span className="s3">&nbsp;</span>신고한<span className="s3">&nbsp;</span>후<span className="s3">,&nbsp;</span>환불<span className="s3">&nbsp;</span>가능<span className="s3">&nbsp;</span>기간을<span className="s3">&nbsp;</span>넘긴<span className="s3">&nbsp;</span>경우<span className="s3">.<br /></span>환불<span className="s3">&nbsp;</span>가능<span className="s3">&nbsp;</span>기간<span className="s3">&nbsp;</span>이후<span className="s3">&nbsp;</span>신고<span className="s3">&nbsp;</span>취소를<span className="s3">&nbsp;</span>요청한<span className="s3">&nbsp;</span>경우<span className="s3">.<br /></span>환불을<span className="s3">&nbsp;</span>위한<span className="s3">&nbsp;</span>신고<span className="s3">&nbsp;</span>취소<span className="s3">&nbsp;</span>접수증이나<span className="s3">&nbsp;</span>신규<span className="s3">&nbsp;</span>접수증<span className="s3">&nbsp;</span>제출을<span className="s3">&nbsp;</span>거부할<span className="s3">&nbsp;</span>경우</li>
        <li className="li3">수수료<span className="s3">&nbsp;</span>환불과<span className="s3">&nbsp;</span>관련해서는<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약<span className="s3">&nbsp;</span>제<span className="s3">7</span>조<span className="s3">&nbsp;</span>제<span className="s3">1</span>항<span className="s3">,&nbsp;</span>제<span className="s3">2</span>항에<span className="s3">&nbsp;</span>따른<span className="s3">&nbsp;</span>업무수행의<span className="s3">&nbsp;</span>불능사유<span className="s3">&nbsp;</span>또는<span className="s3">&nbsp;</span>제<span className="s3">8</span>조<span className="s3">&nbsp;</span>제<span className="s3">1</span>항에<span className="s3">&nbsp;</span>해당되는<span className="s3">&nbsp;</span>경우로서<span className="s3">&nbsp;</span>그<span className="s3">&nbsp;</span>책임이<span className="s3">&nbsp;</span>갑의<span className="s3">&nbsp;</span>귀책인<span className="s3">&nbsp;</span>경우에는<span className="s3">&nbsp;</span>세무대리<span className="s3">&nbsp;</span>업무<span className="s3">&nbsp;</span>관련된<span className="s3">&nbsp;</span>수수료와<span className="s3">&nbsp;</span>실비를<span className="s3">&nbsp;</span>을에게<span className="s3">&nbsp;</span>전액<span className="s3">&nbsp;</span>지급해야<span className="s3">&nbsp;</span>하고<span className="s3">,&nbsp;</span>제<span className="s3">8</span>조<span className="s3">&nbsp;</span>제<span className="s3">2</span>항<span className="s3">&nbsp;</span>단서에<span className="s3">&nbsp;</span>따른<span className="s3">&nbsp;</span>계약해지<span className="s3">&nbsp;</span>사유가<span className="s3">&nbsp;</span>을의<span className="s3">&nbsp;</span>귀책인<span className="s3">&nbsp;</span>경우에는<span className="s3">&nbsp;</span>갑에게<span className="s3">&nbsp;</span>환불을<span className="s3">&nbsp;</span>진행합니다<span className="s3">.</span></li>
      </ol>
      <p className="p2"><br /></p>
      <ol className="ol1">
        <li className="li3"><strong>자료</strong><span className="s3"><strong>&nbsp;</strong></span><strong>등의</strong><span className="s3"><strong>&nbsp;</strong></span><strong>제공의무</strong><span className="s3"><strong>&nbsp;</strong></span><strong>및</strong><span className="s3"><strong>&nbsp;</strong></span><strong>책임</strong></li>
        <li className="li3">갑은<span className="s3">&nbsp;</span>위임업무의<span className="s3">&nbsp;</span>수행에<span className="s3">&nbsp;</span>필요한<span className="s3">&nbsp;</span>모든<span className="s3">&nbsp;</span>자료를<span className="s3">&nbsp;</span>을에게<span className="s3">&nbsp;</span>제공하여야<span className="s3">&nbsp;</span>합니다<span className="s3">.</span></li>
        <li className="li3">을의<span className="s3">&nbsp;</span>세무대리업무에<span className="s3">&nbsp;</span>필요한<span className="s3">&nbsp;</span>갑의<span className="s3">&nbsp;</span>자료는<span className="s3">&nbsp;IT</span>솔루션사를<span className="s3">&nbsp;</span>통해서<span className="s3">&nbsp;</span>을에게<span className="s3">&nbsp;</span>제공됩니다<span className="s3">.&nbsp;</span>단<span className="s3">,&nbsp;</span>앱서비스를<span className="s3">&nbsp;</span>통해<span className="s3">&nbsp;</span>전달될<span className="s3">&nbsp;</span>수<span className="s3">&nbsp;</span>없거나<span className="s3">&nbsp;</span>전달되지<span className="s3">&nbsp;</span>못한<span className="s3">&nbsp;</span>자료<span className="s3">&nbsp;</span>요청<span className="s3">&nbsp;</span>시<span className="s3">&nbsp;</span>갑은<span className="s3">&nbsp;</span>해당<span className="s3">&nbsp;</span>자료를<span className="s3">&nbsp;</span>을에게<span className="s3">&nbsp;</span>제공하여야<span className="s3">&nbsp;</span>합니다<span className="s3">.</span></li>
      </ol>
      <p className="p2"><br /></p>
      <ol className="ol1">
        <li className="li4"><span className="s4"><strong>의무</strong></span></li>
      </ol>
      <p className="p3">갑은<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약에서<span className="s3">&nbsp;</span>정의한<span className="s3">&nbsp;</span>의무수행에<span className="s3">&nbsp;</span>필요한<span className="s3">&nbsp;</span>증빙자료와<span className="s3">&nbsp;</span>제반서류<span className="s3">&nbsp;</span>및<span className="s3">&nbsp;</span>서면증빙<span className="s3">&nbsp;</span>또는<span className="s3">&nbsp;</span>구두방법<span className="s3">&nbsp;</span>구술내용<span className="s3">(</span>이하<span className="s3">&nbsp;‘</span>과세자료<span className="s3">&nbsp;</span>등<span className="s3">’</span>이라<span className="s3">&nbsp;</span>함<span className="s3">)</span>을<span className="s3">&nbsp;</span>신속<span className="s3">·</span>정확하게<span className="s3">&nbsp;</span>을에게<span className="s3">&nbsp;</span>제공하여야<span className="s3">&nbsp;</span>하며<span className="s3">,&nbsp;</span>을은<span className="s3">&nbsp;</span>갑이<span className="s3">&nbsp;</span>제공한<span className="s3">&nbsp;</span>과세자료에<span className="s3">&nbsp;</span>의해<span className="s3">&nbsp;</span>합리적이고<span className="s3">&nbsp;</span>타당한<span className="s3">&nbsp;</span>회계기준<span className="s3">&nbsp;</span>및<span className="s3">&nbsp;</span>조세법령에<span className="s3">&nbsp;</span>따라<span className="s3">&nbsp;</span>성실하게<span className="s3">&nbsp;</span>제<span className="s3">1</span>조에서<span className="s3">&nbsp;</span>정의한<span className="s3">&nbsp;</span>업무를<span className="s3">&nbsp;</span>수행하여야<span className="s3">&nbsp;</span>합니다<span className="s3">.</span></p>
      <p className="p2"><br /></p>
      <ol className="ol1">
        <li className="li3"><strong>비밀보장</strong><span className="s3"><strong>&nbsp;</strong></span><strong>및</strong><span className="s3"><strong>&nbsp;</strong></span><strong>신의성실</strong></li>
      </ol>
      <p className="p3">을은<span className="s3">&nbsp;</span>업무상<span className="s3">&nbsp;</span>알게<span className="s3">&nbsp;</span>된<span className="s3">&nbsp;</span>갑의<span className="s3">&nbsp;</span>신분상<span className="s3">&nbsp;</span>또는<span className="s3">&nbsp;</span>업무상의<span className="s3">&nbsp;</span>비밀을<span className="s3">&nbsp;</span>타인에게<span className="s3">&nbsp;</span>누설하거나<span className="s3">&nbsp;</span>도용해서는<span className="s3">&nbsp;</span>안되며<span className="s3">,&nbsp;</span>신의로서<span className="s3">&nbsp;</span>성실하게<span className="s3">&nbsp;</span>위임<span className="s3">&nbsp;</span>업무를<span className="s3">&nbsp;</span>수행합니다<span className="s3">.</span></p>
      <p className="p2"><br /></p>
      <ol className="ol1">
        <li className="li3"><strong>업무</strong><span className="s3"><strong>&nbsp;</strong></span><strong>수행불능</strong><span className="s3"><strong>&nbsp;</strong></span><strong>및</strong><span className="s3"><strong>&nbsp;</strong></span><strong>책임</strong></li>
        <li className="li3">갑이<span className="s3">&nbsp;</span>제공한<span className="s3">&nbsp;</span>과세자료가<span className="s3">&nbsp;</span>불비하거나<span className="s3">&nbsp;</span>사기<span className="s3">·</span>부정<span className="s3">&nbsp;</span>또는<span className="s3">&nbsp;</span>허위사유로<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약업무<span className="s3">&nbsp;</span>수행이<span className="s3">&nbsp;</span>불가능할<span className="s3">&nbsp;</span>경우에<span className="s3">&nbsp;</span>발생하는<span className="s3">&nbsp;</span>문제에<span className="s3">&nbsp;</span>대해서는<span className="s3">&nbsp;</span>을은<span className="s3">&nbsp;</span>그<span className="s3">&nbsp;</span>책임을<span className="s3">&nbsp;</span>지지<span className="s3">&nbsp;</span>않습니다</li>
        <li className="li3">을은<span className="s3">&nbsp;</span>갑이<span className="s3">&nbsp;</span>제공한<span className="s3">&nbsp;</span>제<span className="s3">5</span>조에<span className="s3">&nbsp;</span>따른<span className="s3">&nbsp;</span>과세자료가<span className="s3">&nbsp;</span>신의성실한<span className="s3">&nbsp;</span>것으로<span className="s3">&nbsp;</span>간주하여<span className="s3">&nbsp;</span>신고대리하는<span className="s3">&nbsp;</span>것이므로<span className="s3">&nbsp;</span>갑이<span className="s3">&nbsp;</span>제공한<span className="s3">&nbsp;‘</span>과세자료<span className="s3">&nbsp;</span>등<span className="s3">’</span>이<span className="s3">&nbsp;</span>사기<span className="s3">·</span>부정<span className="s3">&nbsp;</span>또는<span className="s3">&nbsp;</span>허위이거나<span className="s3">&nbsp;</span>지연제출<span className="s3">&nbsp;</span>또는<span className="s3">&nbsp;</span>미제출로<span className="s3">&nbsp;</span>인하여<span className="s3">&nbsp;</span>갑에<span className="s3">&nbsp;</span>대한<span className="s3">&nbsp;</span>과세관청의<span className="s3">&nbsp;</span>납세고지<span className="s3">,&nbsp;</span>가산세<span className="s3">,&nbsp;</span>가산금<span className="s3">&nbsp;</span>부과<span className="s3">&nbsp;</span>또는<span className="s3">&nbsp;</span>조세범칙<span className="s3"><span className="Apple-converted-space">&nbsp;&nbsp;</span></span>및<span className="s3">&nbsp;</span>세무조사<span className="s3">&nbsp;</span>등의<span className="s3">&nbsp;</span>처분<span className="s3">(</span>이하<span className="s3">&nbsp;‘</span>행정처분<span className="s3">&nbsp;</span>등<span className="s3">’</span>이라<span className="s3">&nbsp;</span>한다<span className="s3">)</span>이<span className="s3">&nbsp;</span>발생할<span className="s3">&nbsp;</span>경우는<span className="s3">&nbsp;</span>그<span className="s3">&nbsp;</span>발생<span className="s3">&nbsp;</span>시기에<span className="s3">&nbsp;</span>관계없이<span className="s3">&nbsp;</span>갑은<span className="s3">&nbsp;</span>을에게<span className="s3">&nbsp;</span>그<span className="s3">&nbsp;</span>책임을<span className="s3">&nbsp;</span>물을<span className="s3">&nbsp;</span>수<span className="s3">&nbsp;</span>없습니다<span className="s3">.</span></li>
        <li className="li3">천재지변<span className="s3">&nbsp;</span>및<span className="s3">&nbsp;</span>기타<span className="s3">&nbsp;</span>이에<span className="s3">&nbsp;</span>준하는<span className="s3">&nbsp;</span>사유로<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약을<span className="s3">&nbsp;</span>수행할<span className="s3">&nbsp;</span>수<span className="s3">&nbsp;</span>없을<span className="s3">&nbsp;</span>때는<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약<span className="s3">&nbsp;</span>불이행에<span className="s3">&nbsp;</span>따른<span className="s3">&nbsp;</span>책임을<span className="s3">&nbsp;</span>상호간에<span className="s3">&nbsp;</span>묻지<span className="s3">&nbsp;</span>않기로<span className="s3">&nbsp;</span>합니다<span className="s3">.</span></li>
      </ol>
      <p className="p2"><br /></p>
      <ol className="ol1">
        <li className="li4"><span className="s4"><strong>계약의</strong></span><strong>&nbsp;</strong><span className="s4"><strong>해지</strong></span></li>
        <li className="li3">갑의<span className="s3">&nbsp;</span>사정에<span className="s3">&nbsp;</span>의해<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약이<span className="s3">&nbsp;</span>해지될<span className="s3">&nbsp;</span>경우<span className="s3">&nbsp;</span>해지시기<span className="s3">&nbsp;</span>이후부터<span className="s3">&nbsp;</span>발생되는<span className="s3">&nbsp;‘</span>행정처분<span className="s3">&nbsp;</span>등<span className="s3">’</span>에<span className="s3">&nbsp;</span>대하여<span className="s3">&nbsp;</span>을은<span className="s3">&nbsp;</span>그<span className="s3">&nbsp;</span>책임을<span className="s3">&nbsp;</span>지지<span className="s3">&nbsp;</span>아니합니다<span className="s3">.&nbsp;</span>이러한<span className="s3">&nbsp;</span>경우에도<span className="s3">&nbsp;</span>제<span className="s3">2</span>조에<span className="s3">&nbsp;</span>정한<span className="s3">&nbsp;</span>수수료<span className="s3">&nbsp;</span>또는<span className="s3">&nbsp;</span>실비를<span className="s3">&nbsp;</span>을에게<span className="s3">&nbsp;</span>지급하여야<span className="s3">&nbsp;</span>합니다<span className="s3">.</span></li>
        <li className="li3">갑이<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약에<span className="s3">&nbsp;</span>정한<span className="s3">&nbsp;</span>의무를<span className="s3">&nbsp;</span>이행하지<span className="s3">&nbsp;</span>아니하거나<span className="s3">&nbsp;</span>위임사무의<span className="s3">&nbsp;</span>내용에<span className="s3">&nbsp;</span>관하여<span className="s3">&nbsp;</span>제공한<span className="s3">&nbsp;</span>과세자료<span className="s3">&nbsp;</span>등이<span className="s3">&nbsp;</span>불비하거나<span className="s3">&nbsp;</span>허위인<span className="s3">&nbsp;</span>때에는<span className="s3">&nbsp;</span>고의성<span className="s3">&nbsp;</span>여부에<span className="s3">&nbsp;</span>관계없이<span className="s3">&nbsp;</span>을은<span className="s3">&nbsp;</span>이<span className="s3">&nbsp;</span>계약을<span className="s3">&nbsp;</span>일방적으로<span className="s3">&nbsp;</span>계약해지<span className="s3">&nbsp;</span>및<span className="s3">&nbsp;</span>사임할<span className="s3">&nbsp;</span>수<span className="s3">&nbsp;</span>있다<span className="s3">.&nbsp;</span>다만<span className="s3">,&nbsp;</span>을의<span className="s3">&nbsp;</span>사정에<span className="s3">&nbsp;</span>의해<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약업무를<span className="s3">&nbsp;</span>수행하지<span className="s3">&nbsp;</span>못할<span className="s3">&nbsp;</span>경우<span className="s3">&nbsp;</span>을은<span className="s3">&nbsp;</span>그<span className="s3">&nbsp;</span>시기까지<span className="s3">&nbsp;</span>모든<span className="s3">&nbsp;</span>업무를<span className="s3">&nbsp;</span>정리하여<span className="s3">&nbsp;</span>갑에게<span className="s3">&nbsp;</span>인계함으로써<span className="s3">&nbsp;</span>본<span className="s3">&nbsp;</span>계약이<span className="s3">&nbsp;</span>해지된<span className="s3">&nbsp;</span>것으로<span className="s3">&nbsp;</span>간주합니다<span className="s3">.</span></li>
      </ol>
      <p className="p2"><br /></p>
      <ol className="ol1">
        <li className="li4"><span className="s4"><strong>분쟁의</strong></span><strong>&nbsp;</strong><span className="s4"><strong>해결</strong></span></li>
      </ol>
      <p className="p3">계약<span className="s3">&nbsp;</span>당사자<span className="s3">&nbsp;</span>사이에<span className="s3">&nbsp;</span>분쟁이<span className="s3">&nbsp;</span>발생할<span className="s3">&nbsp;</span>경우<span className="s3">&nbsp;</span>일차적으로<span className="s3">&nbsp;</span>계약<span className="s3">&nbsp;</span>당사자<span className="s3">&nbsp;</span>간의<span className="s3">&nbsp;</span>상호<span className="s3">&nbsp;</span>합의와<span className="s3">&nbsp;</span>존중을<span className="s3">&nbsp;</span>바탕으로<span className="s3">&nbsp;</span>해결합니다<span className="s3">.&nbsp;</span>단<span className="s3">,&nbsp;</span>이와<span className="s3">&nbsp;</span>같은<span className="s3">&nbsp;</span>방법으로<span className="s3">&nbsp;</span>해결되지<span className="s3">&nbsp;</span>않고<span className="s3">&nbsp;</span>분쟁이<span className="s3">&nbsp;</span>발생할<span className="s3">&nbsp;</span>경우<span className="s3">&nbsp;</span>서울지방법원을<span className="s3">&nbsp;</span>제<span className="s3">1</span>심<span className="s3">&nbsp;</span>전속관할법원으로<span className="s3">&nbsp;</span>합니다<span className="s3">.</span></p>
      <p className="p2"><br /></p>
      <ol className="ol1">
        <li className="li4"><span className="s4"><strong>기타</strong></span></li>
      </ol>
      <p className="p3">본<span className="s3">&nbsp;</span>계약에<span className="s3">&nbsp;</span>명시되지<span className="s3">&nbsp;</span>아니한<span className="s3">&nbsp;</span>사항은<span className="s3">&nbsp;</span>일반적인<span className="s3">&nbsp;</span>사회통념상의<span className="s3">&nbsp;</span>상관습에<span className="s3">&nbsp;</span>따라<span className="s3">&nbsp;</span>상호합의<span className="s3">&nbsp;</span>하여<span className="s3">&nbsp;</span>정하기로<span className="s3">&nbsp;</span>합니다<span className="s3">.</span></p>
      <p className="p2"><br /></p>
      <p className="p2"><br /></p>
      <p className="p2"><br /></p>
      <p className="p2"><br /></p>
      <p className="p6"><span className="s4"><strong>계약일자</strong></span><strong>&nbsp;2021</strong><span className="s4"><strong>년</strong></span><strong><span className="Apple-converted-space">&nbsp; &nbsp; &nbsp;&nbsp;</span></strong><span className="s4"><strong>월</strong></span><strong>&nbsp;<span className="Apple-converted-space">&nbsp; &nbsp; &nbsp;&nbsp;</span></strong><span className="s4"><strong>일</strong></span></p>
      <p className="p7"><span className="s1"><strong>위임인</strong></span><span className="s5"><strong>&nbsp;</strong></span><span className="s1"><strong>갑</strong></span></p>
      <p className="p8"><span className="s4">주소</span> :</p>
      <p className="p8"><span className="s4">이름</span> :<span className="Apple-converted-space">&nbsp;</span></p>
      <p className="p7">주민등록번호<span className="s3">&nbsp;:<span className="Apple-converted-space">&nbsp;</span></span></p>
      <p className="p9"><br /></p>
      <p className="p7"><span className="s1"><strong>수임인</strong></span><span className="s5"><strong>&nbsp;</strong></span><span className="s1"><strong>을</strong></span></p>
      <p className="p7">주소<span className="s3">&nbsp;:&nbsp;</span>서울<span className="s3">&nbsp;</span>특별시<span className="s3">&nbsp;</span>서초구<span className="s3">&nbsp;</span>방배로<span className="s3">&nbsp;126,&nbsp;</span>석하빌딩<span className="s3">&nbsp;4F</span></p>
      <p className="p7">법인명<span className="s3">&nbsp;:&nbsp;</span>세무법인<span className="s3">&nbsp;</span>다솔<span className="s3">&nbsp;</span>반포중앙지점</p>
      <p className="p8"><span className="s4">사업자등록번호</span> : 114-85-36731</p>
    </div>
    
    )
}
